CREATE TABLE employees (
                            employees_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            full_name VARCHAR(255) NOT NULL,
                            address TEXT,
                            position VARCHAR(100)
);

CREATE TABLE phones (
                          phones_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          number VARCHAR(20) NOT NULL UNIQUE ,
                          type VARCHAR(60)
);

CREATE TABLE employees_phones
(
    employees_id int REFERENCES employees(employees_id),
    phones_id int REFERENCES phones(phones_id),
    PRIMARY KEY (employees_id, phones_id)
);